### ISSUE TITLE
Refactor auth-annotated method to own file and seprate auth providers

### ISSUE THREAD

**Issue by Dr-Horv** [cthit/playIT-python#12]

**Comment by lindskogen** [comment]
This is for chalmerslan and auth right?

**Comment by Dr-Horv** [comment]
@lindskogen Partly yes, to allow more easily/dynamic switching between different authentication backends.

**Comment by Dr-Horv** [comment]
Solved in 2813a57fe4f1ee9efe592b7d72319505da9836cf
