### ISSUE TITLE
Remove old websocket connections when they close

### ISSUE THREAD

**Issue by lindskogen** [cthit/playIT-python#23]

**Comment by Dr-Horv** [comment]
This is already done?

**Comment by Dr-Horv** [comment]
Ah, https://github.com/cthit/playIT-python/blob/integration/playlists-and-redux/backend/src/services/clients_service.py#L41 is the cause. Should be seperate try-except

**Comment by Dr-Horv** [comment]
Solved by 85b6cf91d27b230e486436e9f994aa80a588c70e
